### ISSUE TITLE
使用v2的版本时候，浏览器报错Kr.at is not a function index.js报错的

### ISSUE THREAD

**Issue by fuce1314** [peng0928/SpiderCrawlPlug#1]
我发现一个问题，使用v2的版本时候，浏览器报错Kr.at is not a function  index.js报错的

**Comment by peng0928** [comment]
可以更详细一点嘛，比如提供一下截图我看看。

**Comment by fuce1314** [comment]
国产电脑可能chrome内核版本不支持vue 里面的vuetify 插件

**Comment by peng0928** [comment]
> 国产电脑可能chrome内核版本不支持vue 里面的vuetify 插件

我用的window和mac最新版的chrome都可以的，请问你的是什么版本的chrome呢

**Comment by fuce1314** [comment]
我看到的内核好像是 88 还是86

**Comment by peng0928** [comment]
> 我看到的内核好像是 88 还是86

好像有点低了，您要不尝试下一个新版的，可以参考一下我的版本
![image](https://github.com/user-attachments/assets/691ac1a4-15d6-43b3-85af-d447d105d01f)

**Comment by peng0928** [comment]
> > 我看到的内核好像是 88 还是86
> 
> 好像有点低了，您要不尝试下一个新版的，可以参考一下我的版本 ![image](https://private-user-images.githubusercontent.com/84308519/352542614-691ac1a4-15d6-43b3-85af-d447d105d01f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwMDAxOTMsIm5iZiI6MTcyMTk5OTg5MywicGF0aCI6Ii84NDMwODUxOS8zNTI1NDI2MTQtNjkxYWMxYTQtMTVkNi00M2IzLTg1YWYtZDQ0N2QxMDVkMDFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDEzMTgxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhN2ZlZjEzMjFiODBjNTlhMWVjNDU4MjljYjUzNjBlYWQ2ZWUxMTY2ODhhOWNhOGU0YjYwMWM5Njk0YzA4MjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TnczgRMwvmsp8CNTqbPaapjAMSgo_BinailVd0ka_3o)

**Comment by fuce1314** [comment]
大哥哟，国产电脑，说明是做政企开发的能支持插件已经很不错了。我的意思有没有办法能把这个vuetify  插件替换掉用 layyui 或者其他的，这样比较好

**Comment by fuce1314** [comment]
你没能坚持你的v1版本，用的bootstarp， 其实v1是支持的只不过那个 开关按钮无法关闭监听

**Comment by peng0928** [comment]
> 你没能坚持你的v1版本，用的bootstarp， 其实v1是支持的只不过那个 开关按钮无法关闭监听

可以的，我可以加一下layyui ，我近期优化一下，感谢建议，开关按钮应该可以关闭的。
V1可以通过这边关闭，V1我也更新成这样，目前我更新了，您试试V1的看看：
![image](https://github.com/user-attachments/assets/10e7f5ea-82bf-4785-bef8-994ccabee510)

**Comment by fuce1314** [comment]
因为国产电脑基本都是老版本的chrome内核，所以vue3支持不友好

**Comment by peng0928** [comment]
> 因为国产电脑基本都是老版本的chrome内核，所以vue3支持不友好

确实，当时可能没有考虑到。您在试试V1的

**Comment by fuce1314** [comment]
你下个86内核的吧，这样可以方便调试，我星期一还可以去测试

**Comment by fuce1314** [comment]
其实只要你不用vue就可以实现全兼容

**Comment by fuce1314** [comment]
不得不说，这个抓包真tmd神器，还希望加一个功能就是，导入导出功能

**Comment by peng0928** [comment]
> Quote reply
> Reference in ne



> 不得不说，这个抓包真tmd神器，还希望加一个功能就是，导入导出功能

哈哈，目前V1我更新了关闭的按钮，到时候您试试，我到时候下个86的调试看看。导入、导出是指的是curl嘛

**Comment by fuce1314** [comment]
导出就是我不是国产电脑吗，都是内外网隔离的，在国产电脑上不方便分析数据，我导出导入，主要是能方便分析国产电脑导出来的请求数据，我说的核心数据是 head 请求数据 form表单请求数据，以及 repens返回的请求数据，以及head数据，就是请求以及返回的所有数据，你的这个插件核心竞争力就是国产系统上了，因为win的抓包工具太多了

**Comment by fuce1314** [comment]
fiddler这个功能你应该熟悉，他不就是有导入导出功能吗。

**Comment by peng0928** [comment]
> 导出就是我不是国产电脑吗，都是内外网隔离的，在国产电脑上不方便分析数据，我导出导入，主要是能方便分析国产电脑导出来的请求数据，我说的核心数据是 head 请求数据 form表单请求数据，以及 repens返回的请求数据，以及head数据，就是请求以及返回的所有数据，你的这个插件核心竞争力就是国产系统上了，因为win的抓包工具太多了

明白了，感谢大佬的提醒，

> fiddler这个功能你应该熟悉，他不就是有导入导出功能吗。

是的，我优化一下，感谢！

**Comment by peng0928** [comment]
我进行优化了，您在看看，目前报文增加了复制功能，后期会加一下批量导出、导入的功能。

**Comment by fuce1314** [comment]
我这周试试
